CREATE TABLE 'Moods' (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  'name' TEXT NOT NULL
)


CREATE TABLE 'Entries' (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  'date' TEXT NOT NULL,
  'entry' TEXT NOT NULL,
  'mood_id' INTEGER NOT NULL,
  FOREIGN KEY('mood_id') REFERENCES 'Moods'('id')
)

CREATE TABLE 'Tags' (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  'name' TEXT NOT NULL
)

CREATE TABLE 'EntryTags' (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  'entry_id' INTEGER NOT NULL,
  'tag_id' INTEGER NOT NULL,
  FOREIGN KEY('entry_id') REFERENCES 'Entries'('id'),
  FOREIGN KEY('tag_id') REFERENCES 'Tags'('id')
)